[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:80 (Address already in use)
[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:443 (Address already in use)
[17112018 08:11:18] connection connection.c:247-warning: Could not bind 0.0.0.0:69 (Address already in use)
[17112018 08:11:18] connection connection.c:313-warning: Could not bind 0.0.0.0:69 (Address already in use)
[17112018 08:11:18] connection connection.c:316-warning: Could not bind 0.0.0.0:69 (Address already in use)
[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:21 (Address already in use)
[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:42 (Address already in use)
[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:445 (Address already in use)
[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:135 (Address already in use)
[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:5061 (Address already in use)
[17112018 08:11:18] connection connection.c:247-warning: Could not bind 0.0.0.0:5060 (Address already in use)
[17112018 08:11:18] connection connection.c:313-warning: Could not bind 0.0.0.0:5060 (Address already in use)
[17112018 08:11:18] connection connection.c:316-warning: Could not bind 0.0.0.0:5060 (Address already in use)
[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:5060 (Address already in use)
[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:1433 (Address already in use)
[17112018 08:11:18] connection connection.c:227-warning: Could not bind 0.0.0.0:3306 (Address already in use)
[17112018 08:11:18] processor processor.c:346-warning: bistreams/2018-11-17/ <-> bistreams/%Y-%m-%d/
[17112018 08:11:18] python module.c:332-warning: start module.c
[17112018 08:11:18] ihandlers dionaea/ihandlers.py:60-warning: START THE IHANDLERS
[17112018 08:28:36] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 08:28:36] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 08:28:36] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 08:28:38] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 08:29:11] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:5061
[17112018 08:46:22] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 08:46:22] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 08:48:29] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 08:48:29] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 08:57:20] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 08:57:20] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 09:27:27] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 09:27:27] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 09:45:47] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 09:45:47] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 10:39:34] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:5061
[17112018 11:26:40] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 11:26:40] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 11:26:40] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 11:26:40] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 11:26:41] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 11:26:41] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 11:26:41] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 11:26:41] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 11:26:41] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 11:26:41] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 11:26:41] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 11:26:41] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 11:26:42] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 11:26:42] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 11:26:42] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 11:26:42] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 11:44:11] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 11:44:11] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 11:51:56] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 11:51:56] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 12:57:14] ftp dionaea/ftp.py:255-warning: cmd 'b'USER''
[17112018 12:57:14] ftp dionaea/ftp.py:255-warning: cmd 'b'PASS''
[17112018 12:57:14] ftp dionaea/ftp.py:255-warning: cmd 'b'TYPE''
[17112018 12:58:32] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 12:58:32] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 14:05:15] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[17112018 15:40:45] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 15:40:45] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 15:46:43] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 16:20:24] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 16:22:39] ftp dionaea/ftp.py:255-warning: cmd 'b'AUTH''
[17112018 16:40:24] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 16:40:24] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 16:47:49] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'?\x00'
[17112018 16:47:49] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'?\x00'
[17112018 17:06:12] python module.c:1003-warning: TypeError at non-empty format string passed to object.__format__
[17112018 17:06:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/mssql/mssql.py:211 in process
[17112018 17:06:12] python module.c:1029-warning: 	 logger.debug("SQL BATCH : {:.1024s}".format(cmd))
[17112018 17:06:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/mssql/mssql.py:114 in handle_io_in
[17112018 17:06:12] python module.c:1029-warning: 	 r = self.process( self.pendingPacketType, x, chunk)
[17112018 17:06:12] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[17112018 17:06:12] python module.c:1029-warning: 	 None
[17112018 17:22:56] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 17:22:56] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 17:47:54] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 17:51:57] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 17:52:22] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 18:48:59] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 18:48:59] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 18:59:41] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 18:59:41] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 19:00:12] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[17112018 19:11:10] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[17112018 19:11:10] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[17112018 19:11:10] mysqld dionaea/mysql/mysql.py:49-warning: b''
[17112018 19:11:25] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[17112018 19:14:20] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 19:16:37] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 19:16:37] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 21:15:19] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 21:36:48] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00$\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x02'
[17112018 21:36:48] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00$\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x02'
[17112018 21:45:55] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 21:46:02] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 21:46:08] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 21:48:00] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 21:48:06] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 21:48:11] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 21:49:13] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[17112018 23:35:31] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 23:35:31] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 23:47:33] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[17112018 23:47:33] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 00:19:24] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 00:19:24] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 00:19:24] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 00:19:25] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 00:19:25] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 00:19:25] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 00:19:25] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 00:19:26] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 00:19:26] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 00:19:26] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 00:19:26] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 00:19:27] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 00:19:27] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 00:19:27] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 00:19:28] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 00:19:28] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 00:19:29] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 00:19:29] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 00:19:29] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 00:19:30] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 00:55:52] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 00:55:52] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 02:17:35] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 02:17:35] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 02:24:21] tftp dionaea/tftp.py:718-warning: Requested file /var/dionaea/wwwroot/a.pdf does not exist.
[18112018 02:24:21] tftp dionaea/tftp.py:721-warning: Requested file not found: /var/dionaea/wwwroot/a.pdf
[18112018 02:38:54] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[18112018 02:50:17] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'\x00'
[18112018 02:50:17] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'\x00'
[18112018 03:08:07] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[18112018 03:08:07] connection connection.c:168-warning: getpeername failed (Transport endpoint is not connected)
[18112018 03:08:07] connection connection.c:1929-warning: accepting connection failed, closing connection
[18112018 03:08:07] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:1433
[18112018 04:21:51] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 04:21:51] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 04:21:51] mysqld dionaea/mysql/mysql.py:49-warning: b''
[18112018 04:22:00] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 04:22:00] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 04:22:00] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 04:22:00] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 04:22:00] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 04:22:00] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 04:22:06] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 04:22:06] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 04:22:06] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 04:22:06] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 04:22:06] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 04:22:06] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 04:22:21] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 04:22:21] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 04:22:21] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 04:22:21] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 04:22:21] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 04:22:21] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 04:22:27] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 04:22:27] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 04:22:27] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 04:22:27] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 04:22:27] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 04:22:27] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 04:23:22] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[18112018 04:27:11] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 04:27:11] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 04:35:39] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 04:35:39] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 04:47:35] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 04:47:35] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 05:31:59] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 05:31:59] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 05:33:16] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[18112018 05:52:27] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 05:52:27] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 06:35:27] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 06:35:27] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 08:39:46] SMB dionaea/smb/smb.py:655-warning: epmapper - not enough data
[18112018 08:59:44] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[18112018 11:24:41] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 11:24:41] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 12:08:24] connection connection.c:168-warning: getpeername failed (Transport endpoint is not connected)
[18112018 12:08:24] connection connection.c:1929-warning: accepting connection failed, closing connection
[18112018 12:08:24] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:1433
[18112018 12:08:24] connection connection.c:168-warning: getpeername failed (Transport endpoint is not connected)
[18112018 12:08:24] connection connection.c:1929-warning: accepting connection failed, closing connection
[18112018 12:08:24] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:1433
[18112018 13:47:04] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 13:47:04] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 13:47:04] mysqld dionaea/mysql/mysql.py:49-warning: b''
[18112018 13:47:18] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 13:47:18] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 13:47:18] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 13:47:18] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 13:47:18] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 13:47:18] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 13:47:19] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 13:47:19] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 13:47:24] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 13:47:24] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 13:47:24] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 13:47:24] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 13:47:25] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 13:47:25] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 13:47:26] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 13:47:26] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 13:47:31] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 13:47:31] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 13:47:31] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 13:47:31] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 13:47:31] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 13:47:32] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 13:47:50] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[18112018 14:06:22] connection connection.c:168-warning: getpeername failed (Transport endpoint is not connected)
[18112018 14:06:22] connection connection.c:1929-warning: accepting connection failed, closing connection
[18112018 14:06:22] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:1433
[18112018 14:59:59] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 14:59:59] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 15:03:14] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:03:14] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:03:15] mysqld dionaea/mysql/mysql.py:49-warning: b''
[18112018 15:03:23] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:03:23] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:03:24] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:03:24] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:03:24] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 15:03:24] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 15:03:30] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:03:30] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:03:30] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:03:30] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:03:30] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 15:03:30] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 15:03:45] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:03:45] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:03:45] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:03:45] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:03:46] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 15:03:46] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 15:03:51] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:03:51] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:03:51] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:03:51] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:03:52] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 15:03:52] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "show": syntax error
[18112018 15:04:44] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[18112018 15:24:41] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 15:24:41] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 15:58:40] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:58:40] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:58:49] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 15:59:02] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 15:59:06] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:59:06] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:59:06] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 15:59:07] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 15:59:07] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:59:07] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:59:16] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 15:59:17] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 15:59:17] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:59:17] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:59:17] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 15:59:20] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 15:59:21] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:59:21] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:59:21] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 15:59:21] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 15:59:38] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 15:59:38] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 15:59:50] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 16:01:14] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 16:01:14] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 16:01:14] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 16:01:15] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 16:01:15] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 16:01:25] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 16:01:25] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 16:02:01] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 16:02:01] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 16:02:02] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 16:02:02] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 16:02:02] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 16:02:02] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 16:02:06] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 16:02:06] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 16:02:07] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 16:02:07] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 16:02:07] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 16:02:07] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 16:02:08] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 16:02:09] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 16:02:12] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 16:02:12] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 16:02:18] mysqld dionaea/mysql/mysql.py:49-warning: b'mysql'
[18112018 16:02:19] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[18112018 16:02:40] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[18112018 16:07:13] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'\x00'
[18112018 16:07:13] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'\x00'
[18112018 16:20:09] connection connection.c:168-warning: getpeername failed (Transport endpoint is not connected)
[18112018 16:20:09] connection connection.c:1929-warning: accepting connection failed, closing connection
[18112018 16:20:09] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:1433
[18112018 16:20:09] connection connection.c:168-warning: getpeername failed (Transport endpoint is not connected)
[18112018 16:20:09] connection connection.c:1929-warning: accepting connection failed, closing connection
[18112018 16:20:09] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:1433
[18112018 16:37:46] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 16:37:46] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 16:38:17] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[18112018 16:46:14] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[18112018 16:49:16] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[18112018 16:49:41] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[18112018 17:00:17] ftp dionaea/ftp.py:255-warning: cmd 'b'AUTH''
[18112018 17:11:14] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 17:11:14] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 17:53:31] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 17:53:31] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 19:28:43] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 19:28:43] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 19:40:13] python module.c:1003-warning: ReferenceError at ReferenceError('the object requested does not exist',)
[18112018 19:40:13] python module.c:1028-warning: binding.pyx:666 in dionaea.core.connection.local.__get__ (binding.c:7095)
[18112018 19:40:13] python module.c:1029-warning: 	 None
[18112018 19:40:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/sip/__init__.py:365 in __handle_invite
[18112018 19:40:13] python module.c:1029-warning: 	 self.__session.local.host,
[18112018 20:00:29] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 20:00:29] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 20:38:58] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[18112018 21:01:52] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 21:01:52] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[18112018 23:02:59] python module.c:1003-warning: ReferenceError at ReferenceError('the object requested does not exist',)
[18112018 23:02:59] python module.c:1028-warning: binding.pyx:666 in dionaea.core.connection.local.__get__ (binding.c:7095)
[18112018 23:02:59] python module.c:1029-warning: 	 None
[18112018 23:02:59] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/sip/__init__.py:365 in __handle_invite
[18112018 23:02:59] python module.c:1029-warning: 	 self.__session.local.host,
[18112018 23:17:30] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[18112018 23:17:30] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[18112018 23:17:30] mysqld dionaea/mysql/mysql.py:49-warning: b''
[18112018 23:17:30] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[19112018 00:02:00] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[19112018 00:02:00] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[19112018 00:02:00] mysqld dionaea/mysql/mysql.py:49-warning: b''
[19112018 00:02:00] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[19112018 00:23:12] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:12] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:23:12] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:30] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:23:30] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:32] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:23:32] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:43] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:23:43] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:49] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:23:49] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:23:50] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:23:50] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:03] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:24:03] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:09] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:24:09] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:24:23] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:24:23] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:04] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:25:04] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:24] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:25:24] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:25:43] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:25:43] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:03] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:26:03] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:34] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:26:34] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:53] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:26:53] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:26:55] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:26:55] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:13] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:27:13] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:27:45] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:27:45] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:05] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:28:05] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:20] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:28:20] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:28:40] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:28:40] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:06] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:30:06] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:30:26] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:30:26] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:31:55] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:31:55] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:32:15] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:32:15] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:20] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:33:20] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:25] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:33:25] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:40] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:33:40] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1003-warning: AttributeError at AttributeError('Flags2',)
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:889 in getfield_and_val
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:260 in getfield_and_val
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:264 in __getattr__
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/smbfields.py:862 in <lambda>
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:163 in _evalcond
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/fieldtypes.py:180 in size
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:653 in size
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:665 in show
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/include/packet.py:690 in show
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/smb/smb.py:111 in handle_io_in
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:33:45] python module.c:1028-warning: binding.pyx:763 in dionaea.core.handle_io_in_cb (binding.c:8143)
[19112018 00:33:45] python module.c:1029-warning: 	 None
[19112018 00:40:42] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[19112018 00:40:42] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[19112018 00:40:42] mysqld dionaea/mysql/mysql.py:49-warning: b''
[19112018 00:40:42] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[19112018 00:48:20] connection connection.c:168-warning: getpeername failed (Transport endpoint is not connected)
[19112018 00:48:20] connection connection.c:1929-warning: accepting connection failed, closing connection
[19112018 00:48:20] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:1433
[19112018 00:48:20] connection connection.c:168-warning: getpeername failed (Transport endpoint is not connected)
[19112018 00:48:20] connection connection.c:1929-warning: accepting connection failed, closing connection
[19112018 00:48:20] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:1433
[19112018 01:09:18] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[19112018 01:09:18] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[19112018 01:09:18] mysqld dionaea/mysql/mysql.py:49-warning: b''
[19112018 01:09:18] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[19112018 01:41:59] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[19112018 01:41:59] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[19112018 01:41:59] mysqld dionaea/mysql/mysql.py:49-warning: b''
[19112018 01:41:59] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[19112018 01:56:24] python module.c:1003-warning: ReferenceError at ReferenceError('the object requested does not exist',)
[19112018 01:56:24] python module.c:1028-warning: binding.pyx:666 in dionaea.core.connection.local.__get__ (binding.c:7095)
[19112018 01:56:24] python module.c:1029-warning: 	 None
[19112018 01:56:24] python module.c:1028-warning: /usr/lib/dionaea/python/dionaea/sip/__init__.py:365 in __handle_invite
[19112018 01:56:24] python module.c:1029-warning: 	 None
[19112018 02:20:29] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[19112018 02:20:29] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[19112018 02:20:29] mysqld dionaea/mysql/mysql.py:49-warning: b''
[19112018 02:20:29] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[19112018 02:24:47] tftp dionaea/tftp.py:718-warning: Requested file /var/dionaea/wwwroot/a.pdf does not exist.
[19112018 02:24:47] tftp dionaea/tftp.py:721-warning: Requested file not found: /var/dionaea/wwwroot/a.pdf
[19112018 02:30:39] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[19112018 02:30:39] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[19112018 02:40:41] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:443
[19112018 02:50:01] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[19112018 02:50:01] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[19112018 03:00:52] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[19112018 03:00:52] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[19112018 03:00:52] mysqld dionaea/mysql/mysql.py:49-warning: b''
[19112018 03:00:52] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[19112018 03:38:39] mysqld dionaea/mysql/mysql.py:49-warning: information_schema
[19112018 03:38:39] mysqld dionaea/mysql/mysql.py:52-warning: open db information_schema -> :memory:
[19112018 03:38:39] mysqld dionaea/mysql/mysql.py:49-warning: b''
[19112018 03:38:39] mysqld dionaea/mysql/mysql.py:193-warning: SQL ERROR near "set": syntax error
[19112018 03:51:31] connection connection.c:2101-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[19112018 03:51:31] connection connection.c:168-warning: getpeername failed (Transport endpoint is not connected)
[19112018 03:51:31] connection connection.c:1929-warning: accepting connection failed, closing connection
[19112018 03:51:31] logsql dionaea/logsql.py:691-warning: no attackid for ::ffff:10.128.0.3:1433
[19112018 04:02:59] SMB dionaea/smb/smb.py:125-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[19112018 04:02:59] SMB dionaea/smb/smb.py:158-warning: p.haslayer(Raw): b'PATH_R